name: estimate-pm25-python
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core scientific python
  - numpy
  - matplotlib
  - python=3.6
  - seaborn
  - pandas

  # Geo stuff
  - rasterstats
  - geopandas
  - rasterio
  - pysal
  - scikit-learn
  - gdal
  - libgdal
  - geojson
  - ulmo
  - pyhdf

  # Jupyter Environment
  - ipython

  #AWS
  - awscli
