name: estimate-pm25-python
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - numpy
  - matplotlib
  - python=3.6
  - pyqt
  - seaborn
  - pandas

  # Extensions
  - autopep8

  # Geo stuff
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - contextily
  - pysal
  - pyproj
  - folium
  - scikit-image
  - gdal
  - libgdal
  - kealib
  - geocoder
  - geojson
  - ulmo

  # Jupyter Environment
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda


  - pip:
      # Utilities
      - download
      - nbgrader
      - nbclean
      - mne
      - tqdm
      - kiwisolver
      # EA tools via pip
      - mapboxgl
      - sklearn
      - hydrofunctions
      - git+https://github.com/earthlab/estimate-pm25.git